# Generated by Django 3.0.3 on 2020-09-30 03:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200920_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diario', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.TextField()),
                ('descripcion', models.TextField()),
                ('url', models.TextField()),
                ('urlImagen', models.TextField()),
                ('fecha', models.CharField(max_length=50)),
                ('autor', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Preferenci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_noticia', models.IntegerField()),
                ('id_usuario', models.CharField(max_length=50)),
                ('preferencia', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='curso',
            name='curso_publicado',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 29, 22, 18, 4, 574400), verbose_name='Fecha de publicacion'),
        ),
    ]
