# Generated by Django 3.0.3 on 2020-09-30 03:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200929_2218'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Preferenci',
            new_name='Preferencia',
        ),
        migrations.AlterField(
            model_name='curso',
            name='curso_publicado',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 29, 22, 22, 13, 925395), verbose_name='Fecha de publicacion'),
        ),
    ]
