# Generated by Django 3.0.3 on 2020-09-30 03:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200929_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferencia',
            old_name='id_usuario',
            new_name='usuario',
        ),
        migrations.AlterField(
            model_name='curso',
            name='curso_publicado',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 29, 22, 28, 44, 170481), verbose_name='Fecha de publicacion'),
        ),
    ]
