# Generated by Django 3.0.3 on 2020-09-30 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200929_2229'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='id',
            new_name='id_noticia',
        ),
        migrations.AlterField(
            model_name='curso',
            name='curso_publicado',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 30, 2, 33, 21, 214215), verbose_name='Fecha de publicacion'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
