# Generated by Django 3.0.3 on 2020-10-10 03:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20201009_2243'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diario', models.CharField(max_length=50)),
                ('url', models.TextField(max_length=250)),
                ('categoria', models.CharField(choices=[('P', 'Politica'), ('S', 'Salud'), ('E', 'Econpmia')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='curso',
            name='curso_publicado',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 9, 22, 46, 12, 247467), verbose_name='Fecha de publicacion'),
        ),
    ]
