# Generated by Django 3.0.3 on 2020-10-10 03:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201009_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuente',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='curso',
            name='curso_publicado',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 9, 22, 47, 29, 694340), verbose_name='Fecha de publicacion'),
        ),
    ]
